version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo add-apt-repository -y -qq ppa:ubuntu-toolchain-r/test
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install g++-6
            npm install
      - run:
          name: test
          command: npm test
