version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:
          name: install
          command: |
            apt-get -y -qq update
            apt-get -y -qq install g++-6
            npm install
      - run:
          name: test
          command: npm test
