version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt-get -y install software-properties-common
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -y update
            sudo apt-get -y install g++-6
            npm install
      - run:
          name: test
          command: npm test
