version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.11.1-buster
    steps:
      - checkout
      - run:
          name: install
          command: |
            sudo apt -y install lcov
            npm install
      - run:
          name: coverage
          command: npm run ci-coverage
